"""Add products and orders modules

Revision ID: f8e096c23cc1
Revises: 07f54a9ebc9a
Create Date: 2025-12-23 17:26:26.893661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e096c23cc1'
down_revision: Union[str, None] = '07f54a9ebc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id', nullable=False)
    # ### end Alembic commands ###
