"""Day 39: OrderStatus enum + total NUMERIC(12,2) + proper defaults

Revision ID: b2802e64ad58
Revises: 6c2a308a8071
Create Date: 2025-12-07 12:27:45.388474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2802e64ad58'
down_revision: Union[str, Sequence[str], None] = '6c2a308a8071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint('product_categories_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_categories_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_categories_product_id_fkey', 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('product_categories_category_id_fkey', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
