"""Add index to posts.created_at

Revision ID: 039fa7099279
Revises: 7bb0239a0a22
Create Date: 2025-11-28 12:28:30.998055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039fa7099279'
down_revision: Union[str, Sequence[str], None] = '7bb0239a0a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_created_at', table_name='posts')
    # ### end Alembic commands ###
